model:
  name: CustomIndicOCR_CRNN_BiLSTM
  type: CRNN
  weights_path: null

  input_height: 32
  input_channels: 1
  rnn_hidden_size: 256
  num_rnn_layers: 2
  char_list_path: /Users/paarthmiglani/PycharmProjects/manualagent/cultural_artifact_explorer/scripts/data/ocr/char_list.txt
preprocessing:
  image_height: 32
  grayscale: true
  binarization_threshold: null
  invert_colors: false
postprocessing:
  beam_search: false
  beam_width: 5
  confidence_threshold: 0.5
training:
  dataset_path: /Users/paarthmiglani/PycharmProjects/manualagent/data/ocr/images
  annotations_file: /Users/paarthmiglani/PycharmProjects/manualagent/cultural_artifact_explorer/scripts/data/ocr/annotations.csv
    rotate_limit: 5
    scale_limit: 0.1
    shear_limit: 3
    grid_distortion:
      enable: true
      num_steps: 5
      distort_limit: 0.2
    brightness_contrast:
      enable: true
      contrast_limit: 0.2
      brightness_limit: 0.2
    blur:
      enable: true
      blur_limit: 3
    gaussian_noise:
      enable: true
      var_limit:
      - 10.0
      - 50.0
    rotate_max_angle: 5
    scale_max_factor: 0.1
    noise_level: 0.05
  output_dir: models/ocr/
  log_interval: 100
inference:
  device: cpu
  text_detection:
    enable: true
    detection_model_path: null
    detection_threshold: 0.7
    box_threshold: 0.4
    link_threshold: 0.4
    low_text_threshold: 0.4
    word_segmentation: true

